Thu Feb 09 12:57:15 CET 2023 : Apache Derby Network Server - 10.15.2.0 - (1873585) started and ready to accept connections on port 1527
----------------------------------------------------------------
Thu Feb 09 12:57:22 CET 2023:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.15.2.0 - (1873585): instance a816c00e-0186-3609-74db-ffffdba8e8b4 
on database directory C:\Pilger\B_Uebung2\database\B_Uebung with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@2a139a55 
Loaded from file:/C:/Program%20Files/glassfish-6.2.5/glassfish6/javadb/lib/derby.jar
java.vendor=Oracle Corporation
user.dir=C:\Pilger\B_Uebung2\database
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Pilger\B_Uebung2\database
Database Class Loader started - derby.database.classpath=''
Thu Feb 09 13:36:04 CET 2023 Thread[DRDAConnThread_3,5,main] Cleanup action starting
java.sql.SQLException: Failed to start database 'C:/Pilger/B_Uebung/database/B_Uebung' with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@2a139a55, see the next exception for details.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:115)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:141)
	at org.apache.derby.impl.jdbc.Util.seeNextException(Util.java:252)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(EmbedConnection.java:2855)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:411)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:660)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:656)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:654)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:300)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:967)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1476)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1426)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3380)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1210)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1010)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:300)
Caused by: ERROR XJ040: Failed to start database 'C:/Pilger/B_Uebung/database/B_Uebung' with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@2a139a55, see the next exception for details.
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:300)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory.java:170)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:75)
	... 18 more
Caused by: ERROR XBM0C: Missing privilege for operation 'exists' on file 'service.properties': access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:300)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.handleSecPrivException(StorageFactoryService.java:1266)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(StorageFactoryService.java:1203)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.resolveServicePropertiesFiles(StorageFactoryService.java:559)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$500(StorageFactoryService.java:73)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$4.run(StorageFactoryService.java:296)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.getServiceProperties(StorageFactoryService.java:274)
	at org.apache.derby.impl.services.monitor.BaseMonitor.findProviderAndStartService(BaseMonitor.java:1520)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startPersistentService(BaseMonitor.java:999)
	at org.apache.derby.iapi.services.monitor.Monitor.startPersistentService(Monitor.java:598)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4042)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4038)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.jdbc.EmbedConnection.startPersistentService(EmbedConnection.java:4036)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(EmbedConnection.java:2816)
	... 15 more
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
	at java.base/java.io.File.exists(File.java:829)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(StorageFactoryService.java:1201)
	... 28 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Missing privilege for operation 'exists' on file 'service.properties': access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:115)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:230)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(EmbedConnection.java:2849)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:411)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:660)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:656)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:654)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:300)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:967)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1476)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1426)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3380)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1210)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1010)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:300)
Caused by: ERROR XBM0C: Missing privilege for operation 'exists' on file 'service.properties': access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:300)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.handleSecPrivException(StorageFactoryService.java:1266)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(StorageFactoryService.java:1203)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.resolveServicePropertiesFiles(StorageFactoryService.java:559)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$500(StorageFactoryService.java:73)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$4.run(StorageFactoryService.java:296)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.getServiceProperties(StorageFactoryService.java:274)
	at org.apache.derby.impl.services.monitor.BaseMonitor.findProviderAndStartService(BaseMonitor.java:1520)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startPersistentService(BaseMonitor.java:999)
	at org.apache.derby.iapi.services.monitor.Monitor.startPersistentService(Monitor.java:598)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4042)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4038)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.jdbc.EmbedConnection.startPersistentService(EmbedConnection.java:4036)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(EmbedConnection.java:2816)
	... 15 more
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
	at java.base/java.io.File.exists(File.java:829)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(StorageFactoryService.java:1201)
	... 28 more
============= end nested exception, level (1) ===========
============= begin nested exception, level (2) ===========
ERROR XBM0C: Missing privilege for operation 'exists' on file 'service.properties': access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:300)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.handleSecPrivException(StorageFactoryService.java:1266)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(StorageFactoryService.java:1203)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.resolveServicePropertiesFiles(StorageFactoryService.java:559)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$500(StorageFactoryService.java:73)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$4.run(StorageFactoryService.java:296)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.getServiceProperties(StorageFactoryService.java:274)
	at org.apache.derby.impl.services.monitor.BaseMonitor.findProviderAndStartService(BaseMonitor.java:1520)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startPersistentService(BaseMonitor.java:999)
	at org.apache.derby.iapi.services.monitor.Monitor.startPersistentService(Monitor.java:598)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4042)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4038)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.jdbc.EmbedConnection.startPersistentService(EmbedConnection.java:4036)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(EmbedConnection.java:2816)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:411)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:660)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:656)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:654)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:300)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:967)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1476)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1426)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3380)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1210)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1010)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:300)
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
	at java.base/java.io.File.exists(File.java:829)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(StorageFactoryService.java:1201)
	... 28 more
============= end nested exception, level (2) ===========
============= begin nested exception, level (3) ===========
java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
	at java.base/java.io.File.exists(File.java:829)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(StorageFactoryService.java:1201)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.resolveServicePropertiesFiles(StorageFactoryService.java:559)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$500(StorageFactoryService.java:73)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$4.run(StorageFactoryService.java:296)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.getServiceProperties(StorageFactoryService.java:274)
	at org.apache.derby.impl.services.monitor.BaseMonitor.findProviderAndStartService(BaseMonitor.java:1520)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startPersistentService(BaseMonitor.java:999)
	at org.apache.derby.iapi.services.monitor.Monitor.startPersistentService(Monitor.java:598)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4042)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4038)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.jdbc.EmbedConnection.startPersistentService(EmbedConnection.java:4036)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(EmbedConnection.java:2816)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:411)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:660)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:656)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:654)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:300)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:967)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1476)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1426)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3380)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1210)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1010)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:300)
============= end nested exception, level (3) ===========
Cleanup action completed
Thu Feb 09 13:36:04 CET 2023 Thread[DRDAConnThread_3,5,main] (DATABASE = C:/Pilger/B_Uebung/database/B_Uebung), (DRDAID = {7}), Failed to start database 'C:/Pilger/B_Uebung/database/B_Uebung' with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@2a139a55, see the next exception for details.
Thu Feb 09 13:36:04 CET 2023 Thread[DRDAConnThread_3,5,main] (DATABASE = C:/Pilger/B_Uebung/database/B_Uebung), (DRDAID = {7}), Missing privilege for operation 'exists' on file 'service.properties': access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
Thu Feb 09 13:37:44 CET 2023 Thread[DRDAConnThread_4,5,main] Cleanup action starting
java.sql.SQLException: Failed to start database 'C:/Pilger/B_Uebung/database/B_Uebung' with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@2a139a55, see the next exception for details.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:115)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:141)
	at org.apache.derby.impl.jdbc.Util.seeNextException(Util.java:252)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(EmbedConnection.java:2855)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:411)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:660)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:656)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:654)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:300)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:967)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1476)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1426)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3380)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1210)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1010)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:300)
Caused by: ERROR XJ040: Failed to start database 'C:/Pilger/B_Uebung/database/B_Uebung' with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@2a139a55, see the next exception for details.
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:300)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(SQLExceptionFactory.java:170)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:75)
	... 18 more
Caused by: ERROR XBM0C: Missing privilege for operation 'exists' on file 'service.properties': access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:300)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.handleSecPrivException(StorageFactoryService.java:1266)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(StorageFactoryService.java:1203)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.resolveServicePropertiesFiles(StorageFactoryService.java:559)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$500(StorageFactoryService.java:73)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$4.run(StorageFactoryService.java:296)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.getServiceProperties(StorageFactoryService.java:274)
	at org.apache.derby.impl.services.monitor.BaseMonitor.findProviderAndStartService(BaseMonitor.java:1520)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startPersistentService(BaseMonitor.java:999)
	at org.apache.derby.iapi.services.monitor.Monitor.startPersistentService(Monitor.java:598)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4042)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4038)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.jdbc.EmbedConnection.startPersistentService(EmbedConnection.java:4036)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(EmbedConnection.java:2816)
	... 15 more
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
	at java.base/java.io.File.exists(File.java:829)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(StorageFactoryService.java:1201)
	... 28 more
============= begin nested exception, level (1) ===========
java.sql.SQLException: Missing privilege for operation 'exists' on file 'service.properties': access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(SQLExceptionFactory.java:115)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Util.java:230)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(EmbedConnection.java:2849)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:411)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:660)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:656)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:654)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:300)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:967)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1476)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1426)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3380)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1210)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1010)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:300)
Caused by: ERROR XBM0C: Missing privilege for operation 'exists' on file 'service.properties': access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:300)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.handleSecPrivException(StorageFactoryService.java:1266)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(StorageFactoryService.java:1203)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.resolveServicePropertiesFiles(StorageFactoryService.java:559)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$500(StorageFactoryService.java:73)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$4.run(StorageFactoryService.java:296)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.getServiceProperties(StorageFactoryService.java:274)
	at org.apache.derby.impl.services.monitor.BaseMonitor.findProviderAndStartService(BaseMonitor.java:1520)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startPersistentService(BaseMonitor.java:999)
	at org.apache.derby.iapi.services.monitor.Monitor.startPersistentService(Monitor.java:598)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4042)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4038)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.jdbc.EmbedConnection.startPersistentService(EmbedConnection.java:4036)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(EmbedConnection.java:2816)
	... 15 more
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
	at java.base/java.io.File.exists(File.java:829)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(StorageFactoryService.java:1201)
	... 28 more
============= end nested exception, level (1) ===========
============= begin nested exception, level (2) ===========
ERROR XBM0C: Missing privilege for operation 'exists' on file 'service.properties': access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at org.apache.derby.shared.common.error.StandardException.newException(StandardException.java:300)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.handleSecPrivException(StorageFactoryService.java:1266)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(StorageFactoryService.java:1203)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.resolveServicePropertiesFiles(StorageFactoryService.java:559)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$500(StorageFactoryService.java:73)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$4.run(StorageFactoryService.java:296)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.getServiceProperties(StorageFactoryService.java:274)
	at org.apache.derby.impl.services.monitor.BaseMonitor.findProviderAndStartService(BaseMonitor.java:1520)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startPersistentService(BaseMonitor.java:999)
	at org.apache.derby.iapi.services.monitor.Monitor.startPersistentService(Monitor.java:598)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4042)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4038)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.jdbc.EmbedConnection.startPersistentService(EmbedConnection.java:4036)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(EmbedConnection.java:2816)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:411)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:660)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:656)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:654)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:300)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:967)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1476)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1426)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3380)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1210)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1010)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:300)
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
	at java.base/java.io.File.exists(File.java:829)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(StorageFactoryService.java:1201)
	... 28 more
============= end nested exception, level (2) ===========
============= begin nested exception, level (3) ===========
java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1068)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:416)
	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
	at java.base/java.io.File.exists(File.java:829)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.exists(StorageFactoryService.java:1201)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.resolveServicePropertiesFiles(StorageFactoryService.java:559)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.access$500(StorageFactoryService.java:73)
	at org.apache.derby.impl.services.monitor.StorageFactoryService$4.run(StorageFactoryService.java:296)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.services.monitor.StorageFactoryService.getServiceProperties(StorageFactoryService.java:274)
	at org.apache.derby.impl.services.monitor.BaseMonitor.findProviderAndStartService(BaseMonitor.java:1520)
	at org.apache.derby.impl.services.monitor.BaseMonitor.startPersistentService(BaseMonitor.java:999)
	at org.apache.derby.iapi.services.monitor.Monitor.startPersistentService(Monitor.java:598)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4042)
	at org.apache.derby.impl.jdbc.EmbedConnection$4.run(EmbedConnection.java:4038)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.impl.jdbc.EmbedConnection.startPersistentService(EmbedConnection.java:4036)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(EmbedConnection.java:2816)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(EmbedConnection.java:411)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:660)
	at org.apache.derby.iapi.jdbc.InternalDriver$1.run(InternalDriver.java:656)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.apache.derby.iapi.jdbc.InternalDriver.getNewEmbedConnection(InternalDriver.java:654)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:300)
	at org.apache.derby.iapi.jdbc.InternalDriver.connect(InternalDriver.java:967)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(EmbeddedDriver.java:125)
	at org.apache.derby.impl.drda.Database.makeConnection(Database.java:253)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(DRDAConnThread.java:1476)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(DRDAConnThread.java:1426)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(DRDAConnThread.java:3380)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(DRDAConnThread.java:1210)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(DRDAConnThread.java:1010)
	at org.apache.derby.impl.drda.DRDAConnThread.run(DRDAConnThread.java:300)
============= end nested exception, level (3) ===========
Cleanup action completed
Thu Feb 09 13:37:44 CET 2023 Thread[DRDAConnThread_4,5,main] (DATABASE = C:/Pilger/B_Uebung/database/B_Uebung), (DRDAID = {8}), Failed to start database 'C:/Pilger/B_Uebung/database/B_Uebung' with class loader jdk.internal.loader.ClassLoaders$AppClassLoader@2a139a55, see the next exception for details.
Thu Feb 09 13:37:44 CET 2023 Thread[DRDAConnThread_4,5,main] (DATABASE = C:/Pilger/B_Uebung/database/B_Uebung), (DRDAID = {8}), Missing privilege for operation 'exists' on file 'service.properties': access denied ("java.io.FilePermission" "C:\Pilger\B_Uebung\database\B_Uebung\service.properties" "read")
